package core.id;

public record ChunkId(int posx,int posy) {
	//KEPP IN MIN THAT BECAUSE OF AN ERROR OF MY PART IN THIS CASE
	//POSX IS FOR HIGHT
	//POSY IS FOR WIDTH
	//OTHER CLASSES/RECORS MIGHT USE "POSH" AND "POSW" FOR CLARITY
	//INSTEAD OF POSX AND POSY
}
